### ISSUE TITLE
Setting LIVE/TEST

### ISSUE THREAD

**Issue by peterfealey** [jGRUBBS/seko-ruby-api#2]
First of all, thank you so much for writing this Gem. It's proved super useful for a Spree store (Are you using Spree? Your example order number is familiar!) 

I can't quite work out how to define whether the client.rb uses Live/Test URL or what I need to have in my config.rb to set this. I know it's probably obvious but I'm just not seeing it.

**Comment by jGRUBBS** [comment]
Hey Peter,

I'm glad this gem has been helpful to you. I used to work with Spree quite a bit but have since been developing another ruby based ecommerce platform called Sellect for the last few years. That is what I built this gem for originally, though I imagine this gem could work great with Spree. Anyway, to answer your question, when you are instantiating your client object you can pass options to configure the test mode like this:

``` ruby
client = Seko::Client.new(Seko.config[:token], { test_mode: false })
```

As you probably already found out, `test_mode` defaults to true.
Here are a couple lines of interest pertaining to this specifically for further reading:
https://github.com/jGRUBBS/seko-ruby-api/blob/master/lib/seko/client.rb#L177
https://github.com/jGRUBBS/seko-ruby-api/blob/master/lib/seko/client.rb#L185

I will update the README so this is more apparent. Let me know if this helps and if you have anything other questions about Seko / Supplystream as I've experienced and overcome quite a few issues integrating with them.
